open-contracting/deploy

salt/ocds-docs/robots_live.txt
robots.txt is perhaps too clever by half. For two years we haven't been indexing OCDS for PPPs in Google… Anyhow, this should fix it.
=> Fix robots.txt for OCDS documentation

salt/apache/ocds-docs-live.conf.include, salt/apache/ocds-docs-staging.conf.include, tests/test_docs.py
Builds on #47, Closes #2
Make Apache config for OCDS docs easier to read.
- Collect unique statements near top of file.
- Put banner statements together.
Also remove:
- ProxyPass for /i18n, which as far as I can tell is not / no longer returned by the Data Review Tool.
- legacy Directory directive, which already inherits its contents from the other Directory directive.
- review Location directive, as HTTPS is now forced and it can be removed per comments.
----
I'm not sure if order of precendence affects any of the above (I think not?).
=> Small improvements to Apache config for OCDS docs

pillar/top.sls, pillar/toucan_pillar.sls, salt-config/roster, salt/top.sls, salt/toucan.sls
I did the easy renaming related to #35. We can leave that issue open for the renames that involve  moving / deleting old directories, config files, users, etc.
=> Rename ocdskit-web to toucan where this would have no impact on deployments

pillar/top.sls, salt-config/roster, salt/top.sls
@jpmckinney this refactors the kf-process stuff a little and adds the new server. We can remove the old server once we decommission it.
=> Add new kf process server

docs/deploy/create_server.rst
https://github.com/open-contracting/deploy/issues/16
=> docs: We don't need python-concurrent.futures python-msgpack any more

.gitignore, docs/develop/get_started.rst, pillar/common_pillar.sls, pillar/cove_oc4ids_live_maintenance.sls, pillar/cove_ocds_live3_maintenance.sls, pillar/kingfisher_process1_maintenance.sls, pillar/ocds_docs_live_maintenance.sls, pillar/ocds_docs_staging_maintenance.sls, pillar/ocdskingfisher_archive_maintenance.sls, pillar/ocdskingfisher_replica1_maintenance.sls, pillar/prometheus_maintenance.sls, pillar/redash2_maintenance.sls, pillar/standard-search_maintenance.sls, pillar/top.sls, pillar/toucan_maintenance.sls, salt/top.sls, script/update
This PR adds in a new private repo containing a number of salt scripts that set up maintenance. 
You can see these salt scripts here: https://github.com/open-contracting/dogsbody-maintenance
@JimACarter, please can you review the linked salt code.
=> Adding support for new maintenance set up repo

salt/prometheus-client-common.sls
Our PR has now been accepted.  We were tracking the remote repo before we needed to make a change https://github.com/open-contracting/node-exporter-textfile-collector-scripts/commit/4bb930b565879696245f006e737b9e1ce6b3bd6d.  I imagine we'd like to go back to the remote repo so we can receive any updates they have?
I've opened this as a PR as I wasn't sure if we'd want to also delete https://github.com/open-contracting/node-exporter-textfile-collector-scripts and update https://github.com/open-contracting/standard-maintenance-scripts/blob/master/badges.md to point to https://github.com/prometheus-community/node-exporter-textfile-collector-scripts instead?
=> Point back to prometheus-community/node-exporter-textfile-collector-scripts

salt/standard-search.sls, salt/standard-search/elasticsearch-defaults, salt/standard-search/jvm.options
ElasticSearch version 6.x goes end of life on the 20 Nov 2020. 
This pull request updates ES to version 7.x and updates the configs to match. 
I've also made a couple of improvements to how the apt key is stored and consolidating the custom configs together.
Below is the update process. These commands need to be ran in this order on standard-search (unless otherwise specified):
```
rm /etc/apt/sources.list.d/elasticsearch.list
systemctl stop elasticsearch.service
apt-get update && apt-get dist-upgrade
```
Finally we'll want to kick off a re-index of the docs, please can you advise here?
I can see the [deploy-docs.sh script](https://github.com/open-contracting/deploy/blob/master/deploy-docs.sh), is there any docs on how this is called?
We'll also need to update the …
=> Updating elasticsearch to version 7.x and updating configs to match

pillar/common.sls, pillar/prometheus_client.sls, pillar/top.sls, salt/core/firewall/files/firewall.sh
This PR makes a couple of small changes so that it is easier to create temporary dev servers in the future.
Specifically dev servers don't need anything installed for Prometheus.
`pillar/top.sls` was already doing this for `covid19-dev`, I've expanded this for `*-dev` because we will need this on future servers.
=> Handing dev servers dynamically

script/update
Small PR, this change makes sure that the update script is loaded into memory before executing.
Bash scripts by default execute each line as they go, this meant that if an update changed the update script it would run the git pull and update itself, then start executing the new script half way through.
This will be needed when we remove repos like "salt/private".
=> git repo update script enhancement

salt/core/firewall/files/firewall.sh, salt/postgres/files/pg_hba.conf, salt/postgres/init.sls
Enables AppBeat monitoring, closes #205 
Also fixes Postgres not identifying if the service is broken after a service restart, closes #166
=> Allow access to postgres from appbeat IPs

salt/covid19.sls, salt/react_apps/init.sls
=> 258-move-ver-txt-in-covid-salt

pillar/kingfisher.sls, pillar/kingfisher_common.sls, pillar/kingfisher_replica.sls, salt/postgres/backup.sls
I manually ran a pgBackRest Postgres backup this morning it took roughly 2 hours 15 minutes to complete and compressed the backup size down to only 500GB. 
I am very happy with both of these stats :smile: 
Based on this information, I expect AWS S3 to cost roughly $50 - $60 per month.
We can potentially reduce this cost by moving to S3 infrequent access or possibly Glacier.
I don't have good visibility on the number of requests the backup process made which may change this recommendation.
Salt is currently configured to keep the last four full backups (`retention_full`).
This PR enables daily incremental backups with a weekly full backup (running on Wednesday morning).
=> Enabling regular postgres backups

salt/core/journald.sls, salt/top.sls
Setting journald log storage limits as we've seen disk space issues on the live.docs server.
=> Configuring journald in salt

salt/postgres/files/conf/kingfisher-replica1.conf
@jpmckinney small PR setting 1TB limit on Postgres temp file.
This only sets the variable on the replica1 server, would we like this set on kingfisher-process1?
=> Limit temp tables to 1TB

pillar/cove.sls
@jpmckinney I've identified a bug in the cove Apache configuration that is breaking SSL renewal.
Currently `serveraliases` is set to `main.{{grains.fqdn}}` which worked fine for the old hostname `main.cove-live.oc4ids.opencontracting.uk0.bigv.io` but this doesn't work with the new one because `main.ocp01.open-contracting.org` doesn't have any DNS records.
This PR removes the `main.` prefix which works around this, however I am unsure why it was configured this way in the first place?
=> Removing main. alias prefix

salt/docker_apps/init.sls
Otherwise a "`Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'target'`" error is raised
=> fix: docker_apps check for target

salt/prometheus/files/conf-prometheus-rules.yml
This PR increases the alert thresholds for ocp13 / registry to better match the server usage.
While I was in here I took this opportunity to update prometheus monitoring for our internal monitoring standards, including:
* Increasing InstanceDown alert time (we have dedicated uptime monitoring which is more reliable for this)
* Increased Memory alert threshold and removed double alert
* Reduced File System threshold to 85% (some systems will have 5% disk space reserved for only root)
* Tweaking alert timers to further reduce false positives.
* Restructuring the rules file to have alert categories next to each other.
@jpmckinney I haven't deployed any changes to our Prometheus stack before. Are there any other commands that need running to load in these new rules? I couldn't see anything in …
=> Prometheus alert rules

salt/cove.sls
Checking now no further "uploads" files have been created on OCP02 so I presume the app is managing tmp files and closing them correctly. 
This PR addresses when the cove app errors and leaves uploads behind helping protect against disk space running out. 
Closes #359
=> Cove servers /tmp management

docs/develop/update/network.rst, pillar/redash.sls, pillar/registry.sls, salt/core/network/files/netplan_custom.yaml, salt/core/network/init.sls
Improving the Netplan configuration for "custom" set ups and adding the Registry server netplan configs into salt 
This closes #278
When we deploy this it will remove the old hostname - `amy01`- from the server configs. Nothing should be using this any more so we are OK to remove it.
=> Registry netplan configuration

pillar/registry.sls, salt/apache/init.sls, salt/core/systemd/files/apache2.conf
Fixes #286
I didn't use the `systemd` macro because it seemed a bit overkill for what I needed. This approach uploads `/etc/systemd/system/apache2.service.d/customization.conf` which modifies the existing apache2 systemd config file rather than overwriting it.
=> Apache to wait for networking

docs/maintain/elasticsearch.rst, salt/elasticsearch/plugins/readonlyrest.sls
Updating Salt and docs to use ReadonlyREST API simplifying the update process. 
closes #375
=> Updating to ReadonlyREST API

docs/deploy/create_server.rst, docs/develop/update/firewall.rst, docs/develop/update/network.rst, pillar/maintenance.sls, pillar/prometheus_client.sls, pillar/prometheus_server.sls, pillar/prometheus_server_maintenance.sls, pillar/top.sls, salt-config/roster, salt/core/systemd/files/prometheus-alertmanager.service, salt/prometheus/files/conf-prometheus.yml
This PR updates the prometheus server to Ubuntu 22.04 (#381)
**Go Live plan**
```bash
ssh ocp20
systemctl stop prometheus-server.service
rm -rf /home/prometheus-server/data/* # Remove temporary data
ssh ocp03 -p 8255
rsync -avz ocp03:/home/prometheus-server/data/ /home/prometheus-server/data/ # Populate database
systemctl start prometheus-server.service
```
=> Prometheus Ubuntu 22.04

docs/deploy/prometheus.rst, docs/develop/update/apache.rst, docs/develop/update/index.rst, docs/develop/update/languages.rst, docs/develop/update/mysql.rst, docs/develop/update/wordpress.rst, pillar/coalition.sls, pillar/top.sls, salt-config/roster, salt/apache/files/sites/coalition.conf.include, salt/apache/files/sites/wordpress.conf.include, salt/apache/modules/proxy_fcgi.sls, salt/coalition/init.sls, salt/core/network/init.sls, salt/php-fpm/files/default.conf, salt/php-fpm/init.sls, salt/prometheus/files/conf-prometheus.yml, salt/top.sls
PR adds new ocp21, WordPress hosting server for open-spending.eu.
You can test the new site by overwriting your hosts file as follows:
> 139.162.211.65 www.open-spending.eu open-spending.eu
I have configured a self signed SSL cert so you will see an SSL warning until DNS is live.
I have installed WordPress and the new theme (https://github.com/open-contracting-partnership/www.open-spending.eu)
The site will need content changes before we can go live.
=> Coalition Server

pillar/kingfisher_main.sls, salt/postgres/files/ssl/postgresql-certificates-wrapper.sh, salt/postgres/files/ssl/postgresql-certificates.sh, salt/postgres/files/ssl/sudoers, salt/postgres/init.sls
closes #440 
Note that MDCertificateAuthority is set to https://acme-staging-v02.api.letsencrypt.org/directory in pillar/kingfisher_main.sls so that we can remove and get new certificates without going over the rate limit.
I think I have everything configured correctly, and running:
```bash
sudo -u www-data /opt/postgresql-certificates-wrapper.sh "postgres.kingfisher.open-contracting.org"
```
yields the correct result. However, this either isn't being run by MDNotifyCmd, or it's encountering an error (but I don't know how to find a relevant log).
=> postgres: Use Let's Encrypt certificates for PostgreSQL if postgres.ssl.servername is set

salt/docker_apps/files/kingfisher_process.yaml
I used the same directory structure in the containers so that we can use the current command and approach without changes
=> kingfisher: mount users directory to ease local loads

pillar/registry.sls, salt/kingfisher/collect/init.sls, salt/python/extensions.sls, salt/python/init.sls, salt/python/psycopg2.sls, salt/python/virtualenv.sls, salt/python_apps.sls
These states cause an error:
```
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/collect/scrapyd/.ve/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
sys.exit(_main())
File "/home/collect/scrapyd/.ve/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
File "/home/collect/scrapyd/.ve/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
module = importlib.import_module(module_path)
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in …
```
=> python: Allow installing another Python version

docs/deploy/create_server.rst, docs/develop/update/network.rst, pillar/coalition.sls, pillar/cove_oc4ids.sls, pillar/cove_ocds.sls, pillar/credere.sls, pillar/docs.sls, pillar/prometheus_server.sls
@jpmckinney Simple PR adding the new IPv6 blocks we have provisioned.
I am conscious that _if_ there are any errors / issues with this change we will cause an outage.
When is the best time to update and restart networking on these instances?
I was planning on scheduling in this deployment for ~09:00 BST one morning before America wakes up.
=> Add IPv6 addresses to Linode servers

salt/apache/init.sls, salt/docker_apps/files/redash.yaml, salt/docker_apps/init.sls, salt/redash/init.sls, salt/top.sls
@jpmckinney, do we have any standardisation around config file names?
This config file needs to be applied after the other files because it overwrites some of their settings – thus zz-customization.
=> feat: disable apache version numbers

salt/apache/files/sites/_common.conf, salt/apache/files/sites/default.conf.include, salt/apache/init.sls, salt/top.sls
The default site config needs to be the first site in-order to apply correctly.
If the default site is not first then another site will return to "unexpected traffic" such as direct requests to the IP address.
This bug exists on Cove because cove is first alphabetically.
=> Apache default improvements

docs/deploy/create_server.rst, salt/core/firewall/files/firewall.sh, salt/core/motd.sls, salt/core/systemd/ntp.sls
Minor changes preparing Deploy for Ubuntu 24.04.
After deploying, we can delete the following file `/etc/update-motd.d/80-livepatch` on all servers.
This file is no longer present on new installs, however and Salt was creating it as part of the file.managed state.
=> Ubuntu 24.04 support

salt/credere/init.sls
to be merged with https://github.com/open-contracting/credere-backend/pull/380 and https://github.com/open-contracting/credere-backend/pull/381
=> credere: use new format for running commands

docs/deploy/create_server.rst
@jpmckinney , just documenting a manual step I ran on `ocp27`.
Salt doesn't yet support Python 3.12 and needs the below workaround for deployments to work.
This bug only occurs for me on `ocp27` and only after upgrading my PC (both systems are now Ubuntu 24.04 and therefore Python 3.12).
Let me know if this is best documented somewhere else.
=> docs: note salt Python 3.12 bug

pillar/common.sls, pillar/portland_dev.sls, pillar/top.sls, salt/core/mail.sls, salt/prometheus/files/conf-alertmanager.yml
This PR adds relay support to Postfix. We need this on portland-dev in order to send administrative email as they are being blocked by the ISP.
@jpmckinney , `pillar.smtp` is already configured on Credere, but I cannot see where it is in use in Salt?
I re-used `smtp` because it configures the same service this adds to Postfix.
However, if this clashes other parts of the code, we could rename the values in this PR to `pillar.postfix.relay`.
To Do:
=> feat: add postfix relay support

docs/develop/update/docker.rst, pillar/cms.sls, pillar/common.sls, pillar/cove.sls, pillar/dreambi.sls, pillar/registry.sls, salt/core/swap.sls, salt/core/sysctl.sls, salt/postgres/init.sls, salt/top.sls
We are now configuring more kernel parameters with sysctl and for multiple services. This PR consolidates the setting of kernel parameters into one, dynamic core file.
This function needed extracting because `overcommit_memory` should be configured for both Redis and PostgreSQL.
@jpmckinney , I think, it would be beneficial to add a prompt in the docs to configure `overcommit_memory` when Redis containers in Docker are added. I am not sure where to add this, or how big of a section it should be, please can you advise?
Once merged, the following needs actioning:
Closes #524
=> Sysctl redis

salt/backup/files/site-backup-to-s3.sh, salt/mysql/files/mysql-backup-to-s3.sh, salt/postgres/files/postgres-backup-to-s3.sh
The `tar` command interprets colons in filenames as a remote server to connect too.
This quirk of tar meant that working with our PostgreSQL backups was not straightforward, and importantly, could delay recovery in critical moments.
This PR changes backup file date formats to only include a basic character set while still following iso 8601 standardisation.
I have also added the time to file backups allowing us to backup multiple times in one day.
=> feat: unifying backup date format
