deploy-profile.sh

https://github.com/OpenDataServices/standard-search/issues/9

Add Standard Search to Deploy Profile

---

salt/apache/ocdskingfisherprocess.conf
salt/apache/ocdskingfisherscrape.conf
salt/ocdskingfisherscrape.sls

A little cleanup (not related to https://github.com/open-contracting/kingfisher-process/issues/158).

Remove old Kingfisher ServerAlias

---

pillar/cove_oc4ids_live_pillar.sls
pillar/cove_ocds_live_pillar.sls
pillar/live_pillar.sls
salt/apache/cove.conf
salt/cove.sls

- Move variables that change between CoVEs to top of pillar files, to make them easier to compare
- Set variables in pillar files instead of having default values in cove.sls
- Remove default values from cove.sls
- Remove IATI logic
Closes #17. There might be more to do (not sure how to address the SSL comment in #17).

Change servername and allowedhosts for OC4IDS Data Review Tool.

---

salt/apache.sls
salt/apache/cove.conf.include
salt/apache/ocds-legacy.conf
salt/apache/ocdskit-web.conf.include
salt/apache/standard-search.conf.include
salt/lib.sls

As I work on files, it's less work (for me and any person new to the project) if I don't have to think about variables and logic that are not used.

Cleanup: banner_message is not used

---

docs/how-to/update.rst

https://github.com/open-contracting/deploy/issues/39

Docs - notes on V.M.s

---

docs/reference/index.rst

https://github.com/open-contracting/deploy/issues/13

Docs - Monitoring

---

docs/how-to/get_started.rst

Closes https://github.com/open-contracting/deploy/issues/94

Python2 vs python3 issue

---

docs/reference/index.rst

https://github.com/open-contracting/deploy/issues/31
Starting docs with access details - more docs to come after other work has been done.

Docs - start Prometheus details

---

docs/how-to/update.rst
docs/reference/bytemark.rst

https://github.com/open-contracting/deploy/issues/97

docs: Update for new cove server

---

docs/how-to/deploy.rst
docs/how-to/index.rst
docs/how-to/kingfisher.rst
docs/how-to/maintain.rst
docs/how-to/update_server_packages.rst

Also expand section on checking long running tasks on Kingfisher
https://trello.com/c/WZ8JlrZ6/76-deploy-docs-about-server-maintenance

docs: Add instructions on how to update server packages

---

docs/reference/index.rst
pillar/private-templates/prometheus_pillar.sls
salt/private-templates/prometheus-server-alertmanager/conf-alertmanager.yml
salt/private-templates/prometheus-server-blackbox/conf-blackbox.yml
salt/private-templates/prometheus-server-server/conf-prometheus-rules.yml
salt/private-templates/prometheus-server-server/conf-prometheus.yml

https://github.com/open-contracting/deploy/issues/31

Prometheus - Docs and templates for private files

---

docs/deploy/create_server.rst

https://github.com/open-contracting/deploy/issues/16

Docs:add LastPass to create a server

---

docs/deploy/prometheus.rst
docs/develop/update.rst

https://github.com/open-contracting/deploy/issues/108

Docs: Prometheus Upgrades

---

salt/django.sls

This is required to avoid issues with Salt's virtualenv state, and '-r' inside comments added by pip-compile of pip-tools. https://github.com/open-contracting/deploy/issues/130

Run pip directly

---

docs/use/index.rst
docs/use/kingfisher-process.rst

https://github.com/open-contracting/kingfisher-process/issues/277

docs: Add Kingfisher Process Logs

---

docs/use/index.rst
docs/use/kingfisher-process.rst
docs/use/kingfisher-views.rst

https://github.com/open-contracting/kingfisher-views/issues/93

docs: Kingfisher Views; add logging

---

salt/postgres/ocdskingfisher_postgres.conf
salt/postgres11.sls

https://github.com/open-contracting/deploy/issues/144

kingfisher: Add Postgres Specific settings

---

docs/deploy/postgres.rst
pillar/standard_search_pillar.sls
salt/lib/delete-after-x-days.sh
salt/postgres/replica_master.sls

Adding script to clear down WAL archive on Postgres replica master servers after 7 days.
Ref issue #176

Adding script to clear down Postgres WAL archive

---

docs/deploy/kingfisher.rst

https://github.com/open-contracting/deploy/issues/134

docs: Scrapyd isn't restarted on deploy

---

salt/cove.sls

To address issue https://github.com/open-contracting/cove-oc4ids/issues/75

cove: Add memcached server to packages installed

---

docs/use/databases.rst

https://github.com/open-contracting/kingfisher-colab/issues/37

docs: Update Kingfisher Colab database instructions

---

salt/prometheus/node_exporter.sls

Closes https://github.com/open-contracting/deploy/issues/193

Move smartmon.sh to a directory owned by root

---

salt/onboarding.sls

Applies suggestions from and closes #214

Updating onboarding.sls for salt modules

---

pillar/covid19.sls
pillar/top.sls
salt/apache/files/sites/react-js.conf.include
salt/covid19.sls
salt/covid19/init.sls
salt/covid19/public.sls
salt/postgres/init.sls
salt/python_apps.sls
salt/top.sls

covid-19 setup

---

salt/covid19/init.sls
salt/react_apps/init.sls

covid19: 260-execute-ver-txt-function-at-last

---

docs/deploy/create_server.rst
docs/reference/index.rst

Updating documentation for Linode hosting as discussed https://github.com/open-contracting/deploy/issues/145#issuecomment-884100203.

Updating docs for Linode hosting

---

salt/core/systemd/files/scrapyd.service

ref #https://github.com/open-contracting/kingfisher-collect/issues/606

scrapyd.service: increase LimitNOFILE

---

salt/core/systemd/files/scrapyd.service

ref https://github.com/open-contracting/kingfisher-collect/issues/606

scrapyd: fix systemd config file format

---

salt/docker_apps/files/kingfisher_process.yaml
salt/docker_apps/files/pelican_backend.yaml
salt/docker_apps/files/pelican_frontend.yaml
salt/docker_apps/files/registry.yaml

To be merged after/with:
- https://github.com/open-contracting/kingfisher-process/pull/347
- https://github.com/open-contracting/data-registry/pull/173
- https://github.com/open-contracting/pelican-frontend/pull/72
- https://github.com/open-contracting/deploy-pillar-private/pull/22

registry: remove local network mode

---

salt/kingfisher/collect/incremental.sls

To be deployed after https://github.com/open-contracting/kingfisher-collect/pull/878 is deployed

incremental: add chile

---

docs/develop/update/elasticsearch.rst
pillar/docs.sls
salt/elasticsearch/files/pem-to-keystore-wrapper.sh
salt/elasticsearch/files/sudoers.d/pem-to-keystore
salt/elasticsearch/plugins/readonlyrest.sls

Simple solution to fix ElasticSearch SSL certificate renewal automation.

Fixing ElasticSearch SSL renewal

---

pillar/registry.sls
salt/docker_apps/files/spoonbill.yaml

to be merged after https://github.com/open-contracting/spoonbill-web/pull/413

spoonbill: add volume to ngnix to serve media files

---

salt/kingfisher/collect/incremental.sls

to be merged with https://github.com/open-contracting/kingfisher-collect/pull/900

collect: incremental: fix for Chile

---

docs/maintain/hosting.rst

Documenting how to use the Hetzner rescue system #353 
Also adding notes for Linode recovery.

Adding documentation around recovery sessions

---

docs/develop/update/index.rst
docs/develop/update/mysql.rst
docs/develop/update/postgres.rst
salt/mysql/files/defaults.cnf
salt/mysql/init.sls
salt/postgres/init.sls
salt/top.sls

Adding MySQL support ready for the CRM #298.
This PR does not include support for MySQL backups but this is a future improvement we will need.
I will make an issue for this when this is merged in.

MySQL installation

---

.github/workflows/cove-ocds-live-tests.yml
docs/deploy/aws.rst
docs/deploy/redmine.rst
docs/develop/style/pillar.rst
docs/develop/update/awscli.rst
docs/develop/update/index.rst
docs/develop/update/mysql.rst
docs/develop/update/postgres.rst
pillar/redmine.sls
salt/aws/files/aws-settings.local
salt/aws/init.sls
salt/files/mysql-backup-to-s3.sh
salt/files/site-backup-to-s3.sh
salt/lib.sls
salt/mysql/backup.sls
salt/redmine/backup.sls
salt/top.sls

MySQL and Redmine backups to AWS

---

salt/rabbitmq/init.sls

Use official rabbitmq apt repos

---

docs/deploy/create_server.rst
docs/index.rst

docs: add rDNS setup docs

---

salt/credere/init.sls
salt/docker_apps/files/credere_backend.yaml

credere: add cron jobs

---

docs/use/kingfisher-collect.rst

to be merged with https://github.com/open-contracting/kingfisher-collect/issues/861

docs: update docs about kingfisher collect default steps

---

docs/develop/update/docker.rst
pillar/credere_common.sls
pillar/kingfisher_main.sls
pillar/portland_dev.sls
pillar/redash.sls
pillar/registry.sls
salt/core/logrotate/files/docker
salt/core/rsyslog/files/docker.conf
salt/docker/files/daemon-logging.json
salt/docker/init.sls

Configure Docker persistent logs

---

salt/docker/init.sls

feat: add docker rabbitmq service order

---

docs/develop/update/postgres.rst
pillar/credere_production.sls
pillar/kingfisher_main.sls
pillar/registry.sls
salt/backup/init.sls
salt/kingfisher/process/init.sls
salt/mysql/backup.sls
salt/mysql/files/mysql-backup-to-s3.sh
salt/postgres/backup.sls
salt/postgres/files/postgres-backup-to-s3.sh

Add per-database PostgreSQL backups

---

docs/maintain/docker.rst
salt/docker/files/docker-prune.sh
salt/docker/init.sls

Add daily docker tidy up cron

---

pillar/credere_production.sls

to be merged with https://github.com/open-contracting/credere-backend/pull/408

credere: remove statistics

---

docs/develop/update/postgres.rst
pillar/kingfisher_main.sls

Postgres improvements

---

docs/deploy/servers/data-support.rst
docs/develop/update/postgres.rst
pillar/kingfisher_main.sls
salt/kingfisher/collect/files/cron.sh
salt/kingfisher/collect/incremental.sls

449 document incremental updates

---

docs/develop/update/backup.rst
docs/maintain/backup_testing.rst
docs/maintain/index.rst

docs: add backup testing docs
